### ISSUE TITLE
`Unable to load kernel winograd_conv_2d_weight_transform_bfloat16_bc32`

### ISSUE THREAD

**Issue by marckohlbrugge** [filipstrand/mflux#37] opened 2024-09-07 21:33 UTC
Running into the following issue:

```
marc@mbp mflux-tests % mflux-generate --prompt "hello" -m dev
Fetching 8 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 92948.57it/s]
Fetching 7 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 15734.26it/s]
 25%|█████████████████████████████████████▊                                                                                                                 | 1/4 [00:26<01:19, 26.60s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [01:22<00:00, 20.59s/it]
libc++abi: terminating due to uncaught exception of type std::runtime_error: [metal::Device] Unable to load kernel winograd_conv_2d_weight_transform_bfloat16_bc32

zsh: abort      mflux-generate --prompt "hello" -m dev
marc@mbp mflux-tests % /Users/marc/.asdf/installs/python/3.12.4/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

I've tried both the latest main and `pip install -U mflux`. Both are unable to generate any images.

I did successfully generated images 1-2 weeks ago on a previous version of `main`.

I think it might be related to this issue:

https://github.com/ml-explore/mlx/issues/995

**Comment by filipstrand** [comment] 2024-09-08 16:42
Hmm...this looks like it was fixed in mlx a while ago. Just to see if I could reproduce your error, I tried running MFLUX on an older mlx v0.13.0 and I was able to reproduce it:

```
(.venv) filipstrand@M1-MacBook-Pro old-mlx % mflux-generate --model schnell --prompt "Luxury food photograph" --steps 2 --seed 2 -q 8
Fetching 8 files: 100%|████████████████████████████████████████████| 8/8 [00:00<00:00, 59705.40it/s]
Fetching 7 files: 100%|████████████████████████████████████████████| 7/7 [00:00<00:00, 16587.64it/s]
100%|█████████████████████████████████████████████████████████████████| 2/2 [01:02<00:00, 31.20s/it]
libc++abi: terminating due to uncaught exception of type std::runtime_error: [metal::Device] Unable to load kernel winograd_conv_2d_weight_transform_bfloat16_bc32

zsh: abort      mflux-generate --model schnell --prompt "Luxury food photograph" --steps 2  2
```

If you try to update your MLX version to the newest one, I think it should work! If you want to see what version you are running currently, try running `pip show mlx`. My guess is that when you installed MFLUX a while back you might have used another environment with a newer MLX version

**Comment by marckohlbrugge** [comment] 2024-09-08 22:23
Thank you! That solved it.

It's weird, because I did try already upgrading `mlx` (and all other packages for that matter), but for some reason it didn't take. Maybe it required a system restart after.

**Closed** 2024-09-08 22:23 UTC
